env_args:
    initial_account_balance: 100000  # 初始资金
    commission: 0.00025 # 佣金费率,佣金=成交金额*万分之2.5

train_args:
    rl_model: 'PPO' # 可选: 'PPO', 'A2C', 'DDPG', 'TD3'
    stock_code: '600006' # 股票代码
    total_timesteps: 100

#worker_args:
#    server_address: ''
#    num_parallel: 8

