env_args:
    initial_account_balance: 10000  # 初始资金
    commission: 0.00025 #佣金费率,佣金=成交金额*万分之2.5

train_args:
    rl_model: 'PPO' # 'PPO', 'A2C', 'DDPG', 'TD3'
    stock_code: 'sh.600000'
    total_timesteps: 10000

#worker_args:
#    server_address: ''
#    num_parallel: 8

